# Provisioned by terraform
executionRoleArn: arn:aws:iam::875382849197:role/charter-staging-task
family: charter-__ENVIRONMENT__
cpu: '2048'
memory: '4096'
networkMode: awsvpc
requiresCompatibilities: [FARGATE]
containerDefinitions:
  - name: server
    image: __IMAGE__
    workingDirectory: /var/app/headquarters
    command: ['bin/server.js']
    essential: true
    cpu: '768'
    memory: '1536'
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: "/ecs/charter-__ENVIRONMENT__-server"
        awslogs-region: us-west-2
        awslogs-stream-prefix: ecs
    portMappings:
      - containerPort: 5001
        protocol: tcp
  - name: worker
    image: __IMAGE__
    workingDirectory: /var/app/headquarters
    command: ['bin/worker.js']
    essential: true
    cpu: '768'
    memory: '1536'
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: "/ecs/charter-__ENVIRONMENT__-worker"
        awslogs-region: us-west-2
        awslogs-stream-prefix: ecs
  - name: pubsub
    image: __IMAGE__
    workingDirectory: /var/app/headquarters
    command: ['bin/pubsub.js']
    essential: true
    cpu: '256'
    memory: '1024'
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: "/ecs/charter-__ENVIRONMENT__-pubsub"
        awslogs-region: us-west-2
        awslogs-stream-prefix: ecs
    portMappings:
      - containerPort: 5002
        protocol: tcp
