meta:
  version: 23

roles:
  - name: player
    title: Player
    type: traveler

  - name: system
    title: System
    type: scripted

inboxes:
  - name: inbox
    role: system
    address: system@system.com

scenes:
  - name: scene
    title: First scene

cues:
  - name: start
    scene: scene
    title: start

triggers:
  - name: start
    scene: scene
    event: {type: cue_signaled, cue: start}
    actions:
      - name: send_email
        from: inbox
        to: player
        subject: test
        body: |
          # Hello there!

          Greetings from the System

          Sincerely yours
