meta:
  version: 11

roles:
  - name: Player
    title: Player
    type: traveler

  - name: PhoneTree
    title: PhoneTree
    type: scripted

relays:
  - name: relay-1
    for: Player
    as: Player
    with: PhoneTree
    trailhead: true

scenes:
  - name: SCENE-MAIN
    title: Main

clips:
  - name: CLIP-PHONETREE-1
    title: Greetings
    scene: SCENE-MAIN
    transcript: Greetings!! Would you like a refreshing beverage?
    answer_expected: true
    answer_hints: [yes, no]

  - name: CLIP-PHONETREE-1-YES
    title: "yes"
    scene: SCENE-MAIN
    transcript: Here you go!

  - name: CLIP-PHONETREE-1-NO
    title: "no"
    scene: SCENE-MAIN
    transcript: Next time!

triggers:
  - name: t1
    events: [{type: call_received, from: Player, to: PhoneTree}]
    scene: SCENE-MAIN
    actions: [{ name: 'play_clip', clip_name: 'CLIP-PHONETREE-1' }]

  - name: t2
    events: [{type: clip_answered, clip: CLIP-PHONETREE-1}]
    scene: SCENE-MAIN
    actions:
      - name: conditional  
        if: { op: clip_answer_is, response: "yes" }
        actions: [{ name: 'play_clip', clip_name: 'CLIP-PHONETREE-1-YES' }]
        else: [{ name: 'play_clip', clip_name: 'CLIP-PHONETREE-1-NO' }]
