roles:
  - name: Knight
    title: Knight
    actor: false
    user: true

  - name: Sage
    title: Sage
    actor: false
    user: false

relays:
  - name: main
    for: Knight
    as: Knight
    with: Sage
    trailhead: true
    sms_in: true
    sms_out: true

messages:
  - name: MESSAGE-HELLO
    title: Hello
    scene: SCENE-MAIN
    medium: text
    from: Sage
    to: Knight
    content: Why hello there, fine sir/lady/being! What is your name?

  - name: MESSAGE-HELLO-RUDE
    title: Rude
    scene: SCENE-MAIN
    medium: text
    from: Sage
    to: Knight
    content: How rude, not even a greeting! What is your name?

  - name: MESSAGE-RETURN-GREETING
    scene: SCENE-MAIN
    title: Greet
    medium: text
    from: Sage
    to: Knight
    content: Greetings, {{player_name}}. You may now await your righteous quest.

  - name: MESSAGE-QUEST
    scene: SCENE-MAIN
    title: Quest
    medium: text
    from: Sage
    to: Knight
    content: Your quest is... the holy grail!

scenes:
  - name: SCENE-MAIN
    title: Main

triggers:
  - name: hello
    events: [{type: message_sent, from: Knight, to: Sage, medium: text}]
    scene: SCENE-MAIN
    if: not game_started
    actions:
      - { name: set_value, value_ref: game_started, new_value_ref: 'true' }
      - name: conditional
        if: contains event.message.content "hello" or contains event.message.content "hi" or contains event.message.content "hey"
        actions: [{ name: send_message, message_name: MESSAGE-HELLO }]
        else: [{ name: send_message, message_name: MESSAGE-HELLO-RUDE }]

  - name: getname
    events: [{type: message_sent, from: Knight, to: Sage, medium: text}]
    scene: SCENE-MAIN
    if: game_started
    actions:
      - { name: set_value, value_ref: player_name, new_value_ref: event.message.content }
      - { name: send_message, message_name: MESSAGE-RETURN-GREETING }
      - { name: send_message, message_name: MESSAGE-QUEST, when: in 10s }
