meta:
  version: 13

roles:
  - name: Knight
    title: Knight
    type: traveler

  - name: Sage
    title: Sage
    type: scripted

relays:
  - name: main
    for: Knight
    as: Knight
    with: Sage
    trailhead: true

scenes:
  - name: SCENE-MAIN
    title: Main

triggers:
  - name: hello
    events: [{type: text_received, from: Knight, to: Sage}]
    scene: SCENE-MAIN
    active_if:
      op: not
      item:
        op: istrue
        ref: game_started
    actions:
      - { name: set_value, value_ref: game_started, new_value_ref: 'true' }
      - name: conditional
        if:
          op: or
          items:
            - op: contains
              string_ref: event.message.content
              part_ref: '"hello"'
            - op: contains
              string_ref: event.message.content
              part_ref: '"hi"'
            - op: contains
              string_ref: event.message.content
              part_ref: '"hey"'
        actions:
          - name: send_text
            from_role_name: Sage
            to_role_name: Knight
            content: Why hello there, fine sir/lady/being! What is your name?
        else:
          - name: send_text
            from_role_name: Sage
            to_role_name: Knight
            content: How rude, not even a greeting! What is your name?

  - name: getname
    events: [{type: text_received, from: Knight, to: Sage}]
    scene: SCENE-MAIN
    active_if:
      op: istrue
      ref: game_started
    actions:
      - name: set_value
        value_ref: player_name
        new_value_ref: event.message.content
      - name: send_text
        from_role_name: Sage
        to_role_name: Knight
        content: Greetings, {{player_name}}. You may now await your righteous quest.
      - name: send_text
        from_role_name: Sage
        to_role_name: Knight
        content: Your quest is... the holy grail!
        offset: 10s
