meta:
  version: 12

layouts:
  - name: tablet
    title: Tablet
    type: tabs
    section: tabs
    header_panels:
      - type: text
        style: quest
        text: "{{Player.directive}}"
        visible_if:
          op: istrue
          ref: Player.directive
    
content_pages:
  - name: nav
    section: tabs
    title: Navigation
    panels:
      - type: outlet
        name: main
  - name: messages
    section: tabs
    title: Messages
    panels:
      - type: messages_browse
        title: Messages

roles:
  - name: Player
    title: Player
    type: traveler
    starting_page: PAGE-START
    layout: tablet

  - name: Guide
    title: Guide
    type: scripted

scenes:
  - name: SCENE-MAIN
    title: Main

pages:
  - name: PAGE-START
    title: Start at house
    role: Player
    scene: SCENE-MAIN
    directive: Walk to Atlas
    panels:
      - type: directions
        geofence: GEOFENCE-ATLAS
        waypoint: WAYPOINT-ATLAS
        cue: CUE-ATLAS-ARRIVE

  - name: PAGE-ATLAS
    title: At Atlas Cafe
    role: Player
    scene: SCENE-MAIN
    directive: Enjoy Atlas Cafe!
    waypoint: WAYPOINT-ATLAS

waypoints:
  - name: WAYPOINT-COTTAGE
    title: Cottage
    options:
      - name: cottage
        title: Cottage
        coords: [37.758273, -122.411681]
  - name: WAYPOINT-ATLAS
    title: Atlas Cafe
    options:
      - name: atlas
        title: Atlas Cafe
        coords: [37.759010, -122.411497]
  - name: WAYPOINT-BON-NENE
    title: Bon Nene
    options:
      - name: bonnene
        title: Bon Nene
        coords: [37.757528, -122.411499]

geofences:
  - name: GEOFENCE-ATLAS
    center: WAYPOINT-ATLAS
    distance: 50
  - name: GEOFENCE-BON-NENE
    center: WAYPOINT-BON-NENE
    distance: 20

cues:
  - { name: CUE-ATLAS-ARRIVE, scene: SCENE-MAIN, title: Atlas Cafe Arrived }

triggers:
  - name: atlas
    events: [{ type: cue_signaled, cue: CUE-ATLAS-ARRIVE }]
    scene: SCENE-MAIN
    actions:
      - name: send_message
        message_name: MESSAGE-ATLAS-WELCOME
        to_role_name: Player
      - name: send_to_page
        role_name: Player
        page_name: PAGE-ATLAS

  - name: msg
    events:
      - type: message_received
        medium: image
        from: Player
        to: Guide
        geofence: GEOFENCE-ATLAS
    scene: SCENE-MAIN
    actions:
      - name: send_message
        message_name: MESSAGE-ATLAS-REC
        to_role_name: Player
        offset: 10s
      - name: increment_value
        value_ref: points
        delta: 5

  - name: geofence
    events:
      - type: geofence_entered
        role: Player
        geofence: GEOFENCE-BON-NENE
    scene: SCENE-MAIN
    actions:
      - name: send_message
        message_name: MESSAGE-BON-NENE-WELCOME
        to_role_name: Player
      - name: increment_value
        value_ref: points
        delta: 10

messages:
  - name: MESSAGE-ATLAS-WELCOME
    title: Welcome
    scene: SCENE-MAIN
    medium: text
    from: Guide
    content: Welcome to Atlas Cafe! Send me an picture and i'll give you a sandwich recommendation.

  - name: MESSAGE-ATLAS-REC
    title: Atlas
    scene: SCENE-MAIN
    medium: text
    from: Guide
    content: Try the trout sandwich.

  - name: MESSAGE-BON-NENE-WELCOME
    title: Bon Nene
    scene: SCENE-MAIN
    medium: text
    from: Guide
    content: The mushroom spaghetti bowl is amazing.
