module.exports = {
  ActionsRegistry: require('./registries/actions'),
  ActionCore: require('./cores/action'),
  ActionResultCore: require('./cores/action_result'),
  ConditionCore: require('./cores/condition'),
  ContextCore: require('./cores/context'),
  Errors: require('./errors'),
  EventsRegistry: require('./registries/events'),
  GeofenceCore: require('./cores/geofence'),
  ModulesRegistry: require('./registries/modules'),
  PlayerCore: require('./cores/player'),
  ResourcesRegistry: require('./registries/resources'),
  SceneCore: require('./cores/scene'),
  ScriptCore: require('./cores/script'),
  SubresourcesRegistry: require('./registries/subresources'),
  TemplateUtil: require('./utils/template'),
  TextUtil: require('./utils/text'),
  TimeUtil: require('./utils/time'),
  TripCore: require('./cores/trip'),
  TriggerActionCore: require('./cores/trigger_action'),
  TriggerEventCore: require('./cores/trigger_event'),
  ValidationCore: require('./cores/validation'),
  WaypointCore: require('./cores/waypoint')
};
