name: Deploy to Staging ECS

on: [push]
  # push:
  #   branches: [master]

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: [build, test_core, test_hq]

    - name: Render task definition
      env:
        IMAGE: ${{ steps.login-ecr.outputs.registry }}/charter:${{ github.sha }}
      run: |
        pip install yq
        yq r -j deploy/ecs/task.yaml > /tmp/staging-${{ github.sha }}.json
        sed -i "s/{{IMAGE}}/$IMAGE/g" /tmp/staging-${{ github.sha }}.json
        sed -i "s/{{ENVIRONMENT}}/staging/g" /tmp/staging-${{ github.sha }}.json

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: /tmp/staging-${{ github.sha }}.json
        service: charter-staging
        cluster: charter
        wait-for-service-stability: true
