# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Run tests
on: [push]
jobs:
  test_core:
    name: Test core
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: cd fptcore && npm -q install
    - name: Run tests
      run: cd fptcore && CI=true npm run test

  test_hq:
    name: Test hq
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        (cd fptcore && npm -q install)
        (cd headquarters && npm -q install)
    - name: Run tests
      run: cd headquarters && CI=true npm run test

  lint_agency:
    name: Lint agency
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: cd apps/agency && npm -q install
    - name: Run lint
      run: cd apps/agency && CI=true npm run test

  build_travel:
    name: Build travel
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        cd apps/travel
        npm -q install
        npm -q -g install bower
        bower -q install
        ln -s `pwd`/../../fptcore ./node_modules
    - name: Build
      run: cd apps/travel && CI=true npm run build
